/**
 * This file was autogenerated from Al_seana_16_Bold.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _Al_seana_16_Bold_h_
#define _Al_seana_16_Bold_h_
//---------------------------------------------------------------------------------
extern const unsigned char Al_seana_16_Bold[];
extern const int Al_seana_16_Bold_size;
//---------------------------------------------------------------------------------
#endif //_Al_seana_16_Bold_h_
//---------------------------------------------------------------------------------
