/**
 * This file was autogenerated from background.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _background_h_
#define _background_h_
//---------------------------------------------------------------------------------
extern const unsigned char background[];
extern const int background_size;
//---------------------------------------------------------------------------------
#endif //_background_h_
//---------------------------------------------------------------------------------
