/**
 * This file was autogenerated from blackhole.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _blackhole_h_
#define _blackhole_h_
//---------------------------------------------------------------------------------
extern const unsigned char blackhole[];
extern const int blackhole_size;
//---------------------------------------------------------------------------------
#endif //_blackhole_h_
//---------------------------------------------------------------------------------
