/**
 * This file was autogenerated from competitivebtn.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _competitivebtn_h_
#define _competitivebtn_h_
//---------------------------------------------------------------------------------
extern const unsigned char competitivebtn[];
extern const int competitivebtn_size;
//---------------------------------------------------------------------------------
#endif //_competitivebtn_h_
//---------------------------------------------------------------------------------
