/**
 * This file was autogenerated from optionsbtn.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _optionsbtn_h_
#define _optionsbtn_h_
//---------------------------------------------------------------------------------
extern const unsigned char optionsbtn[];
extern const int optionsbtn_size;
//---------------------------------------------------------------------------------
#endif //_optionsbtn_h_
//---------------------------------------------------------------------------------
