/**
 * This file was autogenerated from pbluevert.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _pbluevert_h_
#define _pbluevert_h_
//---------------------------------------------------------------------------------
extern const unsigned char pbluevert[];
extern const int pbluevert_size;
//---------------------------------------------------------------------------------
#endif //_pbluevert_h_
//---------------------------------------------------------------------------------
