/**
 * This file was autogenerated from pbrown_all.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _pbrown_all_h_
#define _pbrown_all_h_
//---------------------------------------------------------------------------------
extern const unsigned char pbrown_all[];
extern const int pbrown_all_size;
//---------------------------------------------------------------------------------
#endif //_pbrown_all_h_
//---------------------------------------------------------------------------------
