/**
 * This file was autogenerated from resumebtn.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _resumebtn_h_
#define _resumebtn_h_
//---------------------------------------------------------------------------------
extern const unsigned char resumebtn[];
extern const int resumebtn_size;
//---------------------------------------------------------------------------------
#endif //_resumebtn_h_
//---------------------------------------------------------------------------------
