/**
 * This file was autogenerated from selectedbtn.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _selectedbtn_h_
#define _selectedbtn_h_
//---------------------------------------------------------------------------------
extern const unsigned char selectedbtn[];
extern const int selectedbtn_size;
//---------------------------------------------------------------------------------
#endif //_selectedbtn_h_
//---------------------------------------------------------------------------------
