/**
 * This file was autogenerated from singleplayerbtn.png by WiiBuilder.
 */

//---------------------------------------------------------------------------------
#ifndef _singleplayerbtn_h_
#define _singleplayerbtn_h_
//---------------------------------------------------------------------------------
extern const unsigned char singleplayerbtn[];
extern const int singleplayerbtn_size;
//---------------------------------------------------------------------------------
#endif //_singleplayerbtn_h_
//---------------------------------------------------------------------------------
